// This is generated by grok.
// This state is same as my moneyState.java

public class AuthenticatedState implements ATMState {
    @Override
    public void insertCard(ATM atm) {
        System.out.println("Error: Card is already inserted.");
    }

    @Override
    public void enterPin(ATM atm, String pin) {
        System.out.println("Error: PIN is already verified.");
    }

    @Override
    public void withdrawMoney(ATM atm, double amount) {
        if (amount > 0 && amount <= atm.getBalance()) {
            System.out.println("Dispensing $" + amount);
            atm.setBalance(atm.getBalance() - amount);
            System.out.println("Remaining balance: $" + atm.getBalance());
            atm.transitionTo(new IdleState());
        } else {
            System.out.println("Error: Invalid amount or insufficient funds.");
        }
    }

    @Override
    public void ejectCard(ATM atm) {
        System.out.println("Card ejected successfully.");
        atm.transitionTo(new IdleState());
    }
}